---
- name: Make sure the EPEL repository is enabled.
  sudo: yes
  yum: state=present
    name=http://www.gtlib.gatech.edu/pub/fedora-epel/6/i386/epel-release-6-8.noarch.rpm
- name: Install rpm dependencies and development tools of the HaaS.
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - libvirt
    - libvirt-client
    - python-virtinst
    - vconfig
    - bridge-utils
    - telnet
    - qemu-kvm
    - gcc
    - git
    - python-virtualenv
- name: Start libvirtd
  sudo: yes
  service: name=libvirtd state=started enabled=yes
