---
- name: Do operating-system level setup for the HaaS --
    install packages, start services, create users.
  include: os_setup
  sudo: yes
- name: Install the haas and pypi dependencies in the haas user's home dir.
  include: pip
  sudo: yes
  sudo_user: haas
  with_items:
    - moc-rest
    - haas
